summary: "Login to the user Dashboard"
description: "This is a simple API which helps users signup, login and upload a .png file."
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "Accepts input parameters: email and password of string format"
  required: true
  schema:
    type: "object"
    properties:
      email:
        type: "string"
        format: "str"
        example : "example@gmail.com"
      password:
        type: "string"
        format: "str"
        example : "secure_pass"
responses:
  200:
    description: "login success"
  404:
    description: "user not registered"